#!/usr/bin/env python

# Usage: Extract the pl_pokegra.narc file from your existing Platinum ROM
# using a tool such as Tinke, then run this script to extract its assets
# into your pokeplatinum project's folder structure:
#
#   python unpack_pl_pokegra.py
#
# Extracted PNGs will not be optimized for you, so numerous files will
# likely show in the diff. If you wish to optimize your PNGs, then install
# optipng from your distro's package manager, then run the following commands:
#
#   find res/pokemon -name '*_front.png' -exec optipng -clobber -force -strip all -o7 -np {} +
#   find res/pokemon -name '*_back.png' -exec optipng -clobber -force -strip all -o7 -np {} +

import os
import pathlib
import shutil
import subprocess


KNARC = pathlib.Path('./build/subprojects/knarc/knarc')
NITROGFX = pathlib.Path('./build/subprojects/nitrogfx/nitrogfx')
MON_DIRS = [
    '000',
    'bulbasaur',
    'ivysaur',
    'venusaur',
    'charmander',
    'charmeleon',
    'charizard',
    'squirtle',
    'wartortle',
    'blastoise',
    'caterpie',
    'metapod',
    'butterfree',
    'weedle',
    'kakuna',
    'beedrill',
    'pidgey',
    'pidgeotto',
    'pidgeot',
    'rattata',
    'raticate',
    'spearow',
    'fearow',
    'ekans',
    'arbok',
    'pikachu',
    'raichu',
    'sandshrew',
    'sandslash',
    'nidoran_f',
    'nidorina',
    'nidoqueen',
    'nidoran_m',
    'nidorino',
    'nidoking',
    'clefairy',
    'clefable',
    'vulpix',
    'ninetales',
    'jigglypuff',
    'wigglytuff',
    'zubat',
    'golbat',
    'oddish',
    'gloom',
    'vileplume',
    'paras',
    'parasect',
    'venonat',
    'venomoth',
    'diglett',
    'dugtrio',
    'meowth',
    'persian',
    'psyduck',
    'golduck',
    'mankey',
    'primeape',
    'growlithe',
    'arcanine',
    'poliwag',
    'poliwhirl',
    'poliwrath',
    'abra',
    'kadabra',
    'alakazam',
    'machop',
    'machoke',
    'machamp',
    'bellsprout',
    'weepinbell',
    'victreebel',
    'tentacool',
    'tentacruel',
    'geodude',
    'graveler',
    'golem',
    'ponyta',
    'rapidash',
    'slowpoke',
    'slowbro',
    'magnemite',
    'magneton',
    'farfetchd',
    'doduo',
    'dodrio',
    'seel',
    'dewgong',
    'grimer',
    'muk',
    'shellder',
    'cloyster',
    'gastly',
    'haunter',
    'gengar',
    'onix',
    'drowzee',
    'hypno',
    'krabby',
    'kingler',
    'voltorb',
    'electrode',
    'exeggcute',
    'exeggutor',
    'cubone',
    'marowak',
    'hitmonlee',
    'hitmonchan',
    'lickitung',
    'koffing',
    'weezing',
    'rhyhorn',
    'rhydon',
    'chansey',
    'tangela',
    'kangaskhan',
    'horsea',
    'seadra',
    'goldeen',
    'seaking',
    'staryu',
    'starmie',
    'mr_mime',
    'scyther',
    'jynx',
    'electabuzz',
    'magmar',
    'pinsir',
    'tauros',
    'magikarp',
    'gyarados',
    'lapras',
    'ditto',
    'eevee',
    'vaporeon',
    'jolteon',
    'flareon',
    'porygon',
    'omanyte',
    'omastar',
    'kabuto',
    'kabutops',
    'aerodactyl',
    'snorlax',
    'articuno',
    'zapdos',
    'moltres',
    'dratini',
    'dragonair',
    'dragonite',
    'mewtwo',
    'mew',
    'chikorita',
    'bayleef',
    'meganium',
    'cyndaquil',
    'quilava',
    'typhlosion',
    'totodile',
    'croconaw',
    'feraligatr',
    'sentret',
    'furret',
    'hoothoot',
    'noctowl',
    'ledyba',
    'ledian',
    'spinarak',
    'ariados',
    'crobat',
    'chinchou',
    'lanturn',
    'pichu',
    'cleffa',
    'igglybuff',
    'togepi',
    'togetic',
    'natu',
    'xatu',
    'mareep',
    'flaaffy',
    'ampharos',
    'bellossom',
    'marill',
    'azumarill',
    'sudowoodo',
    'politoed',
    'hoppip',
    'skiploom',
    'jumpluff',
    'aipom',
    'sunkern',
    'sunflora',
    'yanma',
    'wooper',
    'quagsire',
    'espeon',
    'umbreon',
    'murkrow',
    'slowking',
    'misdreavus',
    'unown',
    'wobbuffet',
    'girafarig',
    'pineco',
    'forretress',
    'dunsparce',
    'gligar',
    'steelix',
    'snubbull',
    'granbull',
    'qwilfish',
    'scizor',
    'shuckle',
    'heracross',
    'sneasel',
    'teddiursa',
    'ursaring',
    'slugma',
    'magcargo',
    'swinub',
    'piloswine',
    'corsola',
    'remoraid',
    'octillery',
    'delibird',
    'mantine',
    'skarmory',
    'houndour',
    'houndoom',
    'kingdra',
    'phanpy',
    'donphan',
    'porygon2',
    'stantler',
    'smeargle',
    'tyrogue',
    'hitmontop',
    'smoochum',
    'elekid',
    'magby',
    'miltank',
    'blissey',
    'raikou',
    'entei',
    'suicune',
    'larvitar',
    'pupitar',
    'tyranitar',
    'lugia',
    'ho_oh',
    'celebi',
    'treecko',
    'grovyle',
    'sceptile',
    'torchic',
    'combusken',
    'blaziken',
    'mudkip',
    'marshtomp',
    'swampert',
    'poochyena',
    'mightyena',
    'zigzagoon',
    'linoone',
    'wurmple',
    'silcoon',
    'beautifly',
    'cascoon',
    'dustox',
    'lotad',
    'lombre',
    'ludicolo',
    'seedot',
    'nuzleaf',
    'shiftry',
    'taillow',
    'swellow',
    'wingull',
    'pelipper',
    'ralts',
    'kirlia',
    'gardevoir',
    'surskit',
    'masquerain',
    'shroomish',
    'breloom',
    'slakoth',
    'vigoroth',
    'slaking',
    'nincada',
    'ninjask',
    'shedinja',
    'whismur',
    'loudred',
    'exploud',
    'makuhita',
    'hariyama',
    'azurill',
    'nosepass',
    'skitty',
    'delcatty',
    'sableye',
    'mawile',
    'aron',
    'lairon',
    'aggron',
    'meditite',
    'medicham',
    'electrike',
    'manectric',
    'plusle',
    'minun',
    'volbeat',
    'illumise',
    'roselia',
    'gulpin',
    'swalot',
    'carvanha',
    'sharpedo',
    'wailmer',
    'wailord',
    'numel',
    'camerupt',
    'torkoal',
    'spoink',
    'grumpig',
    'spinda',
    'trapinch',
    'vibrava',
    'flygon',
    'cacnea',
    'cacturne',
    'swablu',
    'altaria',
    'zangoose',
    'seviper',
    'lunatone',
    'solrock',
    'barboach',
    'whiscash',
    'corphish',
    'crawdaunt',
    'baltoy',
    'claydol',
    'lileep',
    'cradily',
    'anorith',
    'armaldo',
    'feebas',
    'milotic',
    'castform',
    'kecleon',
    'shuppet',
    'banette',
    'duskull',
    'dusclops',
    'tropius',
    'chimecho',
    'absol',
    'wynaut',
    'snorunt',
    'glalie',
    'spheal',
    'sealeo',
    'walrein',
    'clamperl',
    'huntail',
    'gorebyss',
    'relicanth',
    'luvdisc',
    'bagon',
    'shelgon',
    'salamence',
    'beldum',
    'metang',
    'metagross',
    'regirock',
    'regice',
    'registeel',
    'latias',
    'latios',
    'kyogre',
    'groudon',
    'rayquaza',
    'jirachi',
    'deoxys',
    'turtwig',
    'grotle',
    'torterra',
    'chimchar',
    'monferno',
    'infernape',
    'piplup',
    'prinplup',
    'empoleon',
    'starly',
    'staravia',
    'staraptor',
    'bidoof',
    'bibarel',
    'kricketot',
    'kricketune',
    'shinx',
    'luxio',
    'luxray',
    'budew',
    'roserade',
    'cranidos',
    'rampardos',
    'shieldon',
    'bastiodon',
    'burmy',
    'wormadam',
    'mothim',
    'combee',
    'vespiquen',
    'pachirisu',
    'buizel',
    'floatzel',
    'cherubi',
    'cherrim',
    'shellos',
    'gastrodon',
    'ambipom',
    'drifloon',
    'drifblim',
    'buneary',
    'lopunny',
    'mismagius',
    'honchkrow',
    'glameow',
    'purugly',
    'chingling',
    'stunky',
    'skuntank',
    'bronzor',
    'bronzong',
    'bonsly',
    'mime_jr',
    'happiny',
    'chatot',
    'spiritomb',
    'gible',
    'gabite',
    'garchomp',
    'munchlax',
    'riolu',
    'lucario',
    'hippopotas',
    'hippowdon',
    'skorupi',
    'drapion',
    'croagunk',
    'toxicroak',
    'carnivine',
    'finneon',
    'lumineon',
    'mantyke',
    'snover',
    'abomasnow',
    'weavile',
    'magnezone',
    'lickilicky',
    'rhyperior',
    'tangrowth',
    'electivire',
    'magmortar',
    'togekiss',
    'yanmega',
    'leafeon',
    'glaceon',
    'gliscor',
    'mamoswine',
    'porygon_z',
    'gallade',
    'probopass',
    'dusknoir',
    'froslass',
    'rotom',
    'uxie',
    'mesprit',
    'azelf',
    'dialga',
    'palkia',
    'heatran',
    'regigigas',
    'giratina',
    'cresselia',
    'phione',
    'manaphy',
    'darkrai',
    'shaymin',
    'arceus',
]

pl_pokegra_narc = pathlib.Path('pl_pokegra.narc')
if not pl_pokegra_narc.exists():
    raise IOError('pl_pokegra.narc not found in current working directory')

# Unpack the given pl_pokegra.narc into a working directory
working_dir = pathlib.Path('work')
working_dir.mkdir(parents=True, exist_ok=True)
subprocess.run([
    KNARC,
    '-d', working_dir,
    '-u', pl_pokegra_narc
])

png_order = ['female_back', 'male_back', 'female_front', 'male_front']
res_pokemon_root = pathlib.Path('res/pokemon')

for i in range(494):
    j = i * 6
    res_mon_root = res_pokemon_root / MON_DIRS[i]

    female_back_sprite = working_dir / f'pl_pokegra_{j:08}.NCGR'
    male_back_sprite = working_dir / f'pl_pokegra_{j+1:08}.NCGR'
    female_front_sprite = working_dir / f'pl_pokegra_{j+2:08}.NCGR'
    male_front_sprite = working_dir / f'pl_pokegra_{j+3:08}.NCGR'
    normal_pal = working_dir / f'pl_pokegra_{j+4:08}.NCLR'
    shiny_pal = working_dir / f'pl_pokegra_{j+5:08}.NCLR'

    # Fix extensions on each file
    shutil.move(working_dir / f'pl_pokegra_{j:08}.bin', female_back_sprite)
    shutil.move(working_dir / f'pl_pokegra_{j+1:08}.bin', male_back_sprite)
    shutil.move(working_dir / f'pl_pokegra_{j+2:08}.bin', female_front_sprite)
    shutil.move(working_dir / f'pl_pokegra_{j+3:08}.bin', male_front_sprite)
    shutil.move(working_dir / f'pl_pokegra_{j+4:08}.bin', normal_pal)
    shutil.move(working_dir / f'pl_pokegra_{j+5:08}.bin', shiny_pal)

    # Convert each file
    for k in range(4):
        working_file = working_dir / f'pl_pokegra_{j+k:08}.NCGR'
        if os.stat(working_file).st_size == 0:
            continue

        subprocess.run([
            NITROGFX,
            working_file,
            res_mon_root / f'{png_order[k]}.png',
            '-palette', normal_pal,
            '-scanfronttoback',
            '-handleempty',
        ])

    if i == 0:
        shutil.copy(working_dir / f'pl_pokegra_{j+4:08}.NCLR', res_mon_root / 'normal_pal.NCLR')
        shutil.copy(working_dir / f'pl_pokegra_{j+5:08}.NCLR', res_mon_root / 'shiny_pal.NCLR')
        continue

    subprocess.run([
        NITROGFX,
        normal_pal,
        res_mon_root / 'normal.pal',
        '-bitdepth', '8'
    ])
    subprocess.run([
        NITROGFX,
        shiny_pal,
        res_mon_root / 'shiny.pal',
        '-bitdepth', '8'
    ])
